version: '3.8'

services:
  auth-db:
    image: postgres:14.4-alpine
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auth-service
      POSTGRES_PASSWORD: auth-service
      POSTGRES_DB: auth-service
    volumes:
      - ./AuthService/sql:/docker-entrypoint-initdb.d
  
  
  rest-db:
    image: postgres:14.4-alpine
    container_name: rest-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: rest-service
      POSTGRES_PASSWORD: rest-service
      POSTGRES_DB: rest-service
    volumes:
      - ./RestaurantService/sql:/docker-entrypoint-initdb.d